---

- name: add route to splat mgt firewalls
  hosts: mgtsplatfirewalls
  gather_facts: false

  tasks:      
    # - name: Add hosts routes via interconnect
    #   raw: "route add -host {{ item }} gw 10.240.16.62"
    #   loop:
    #     - '210.54.52.7'
    #     - '210.54.52.10'

    - name: Add network routes via interconnect
      raw: "route add -net {{ item }} gw 10.240.16.62"
      loop:
        - '210.54.52.100/31'
